# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'ME-MngEnv598430-tema-1 (6fa8eb6f-e2f1-493f-b01d-d47253728c9f)'
    azureContainerRegistry: '{"loginServer":"acrmonitoringtest.azurecr.io", "id" : "/subscriptions/6fa8eb6f-e2f1-493f-b01d-d47253728c9f/resourceGroups/rg-aksmonitoringtest/providers/Microsoft.ContainerRegistry/registries/acrmonitoringtest"}'
    dockerComposeFile: '**/docker-compose.yaml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '-d'
