# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'ME-MngEnv598430-tema-1 (6fa8eb6f-e2f1-493f-b01d-d47253728c9f)'
    azureResourceGroup: 'rg-aksmonitoringtest'
    kubernetesCluster: 'aksmonitoringtest'
    useClusterAdmin: true
    namespace: 'vote-devops'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'azure-vote-all-in-one-redis.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

